steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/${PROJECT_ID}/youtubed:$SHORT_SHA', '.' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'gcr.io/${PROJECT_ID}/youtubed:$SHORT_SHA']
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'run'
    - 'deploy'
    - 'youtubed'
    - '--region=us-central1'
    - '--platform=managed'
    - '--allow-unauthenticated'
    - '--service-account=youtubed@big-data-arch-youtubed.iam.gserviceaccount.com'
    - '--image=gcr.io/${PROJECT_ID}/youtubed:$SHORT_SHA'