version: '3'

services:
  backend:
    build: server
    command: ["flask", "run", "--host=0.0.0.0"]
    volumes:
      - ./server:/backend
    env_file: ./server/.env
    environment:
#      - FLASK_ENV=development
      - FLASK_APP=finTest.py
    ports:
      - "5000:5000"

  frontend:
    build: client
    command: ["npm", "start"]
    volumes:
      - ./client:/frontend
      - node-modules:/frontend/node_modules
    environment:
      - NODE_ENV=development
    ports:
      - '3000:3000'
    depends_on:
      - backend
  # nginx:
  #   image: nginx:stable
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro


volumes:
  node-modules: