apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  selector:
    matchLabels:
      component: frontend
  replicas: 1
  template:
    metadata:
      labels:
        component: frontend
    spec:
      containers:
      - name: frontend
        image: gcr.io/big-data-arch-youtubed/frontend
        ports:
        - containerPort: 3000